# Numpy 进阶

In [6]:
import numpy as np

## Numpy数组操作

### 添加元素

numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中

注意：
1. 插入的维度要保证所有数组的长度是相同的
2. 如果没有指定轴，数组会被扁平处理

In [1]:
data = [1,2,3,4]
id(data)

1858635431176

In [2]:
data.append(5)

In [4]:
data

[1, 2, 3, 4, 5]

In [7]:
arr = np.array(data)
id(arr)

1858657816784

In [6]:
arr.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
np.append(arr, 8)
arr

array([1, 2, 3, 4, 5])

In [8]:
arr2 = np.random.randint(0, 10, size=(4,3))
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [12]:
np.append(arr2, [[1,2,3]], axis=0)

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1],
       [1, 2, 3]])

In [14]:
data = np.ones(shape=(4,1))
data

array([[1.],
       [1.],
       [1.],
       [1.]])

In [15]:
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [17]:
np.append(arr2, data, axis=1)

array([[7., 3., 5., 1.],
       [0., 6., 3., 1.],
       [2., 2., 4., 1.],
       [0., 1., 1., 1.]])

### 插入元素

numpy.insert 函数在给定索引之前，沿给定轴在输入数组中插入值

如果未提供轴，则输入数组会被展开

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
np.insert(arr, 2, 100)

array([  1,   2, 100,   3,   4,   5])

In [12]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [23]:
np.insert(arr2, 2, [1,1,1], axis=0)

array([[7, 3, 5],
       [0, 6, 3],
       [1, 1, 1],
       [2, 2, 4],
       [0, 1, 1]])

### 删除元素

numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 

如果未提供轴参数，则输入数组将展开。

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
np.delete(arr, 1)

array([1, 3, 4, 5])

In [26]:
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [28]:
np.delete(arr2, 1, axis=0)

array([[7, 3, 5],
       [2, 2, 4],
       [0, 1, 1]])

### 数组变形reshape

numpy.reshape 函数可以在不改变数据的条件下修改形状，格式如下： numpy.reshape(arr, newshape, order='C')

- arr：要修改形状的数组
- newshape：整数或者整数数组，新的形状应当兼容原有形状
- order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。

In [13]:
arr = np.random.randint(0, 10, size=8)
arr

array([4, 3, 0, 6, 2, 7, 8, 8])

In [14]:
# 不能显示使用shape
# 发现了一些现象： 在numpy中，有些函数的参数名可以写，有些函数的参数名不能写

# 重启解决80%的问题  
# 生活经验解决10%问题
arr.reshape((2,4), order='C')

array([[4, 3, 0, 6],
       [2, 7, 8, 8]])

In [15]:
arr

array([4, 3, 0, 6, 2, 7, 8, 8])

In [32]:
arr.reshape((2,4),order='F')

array([[0, 6, 5, 5],
       [5, 4, 1, 0]])

### 数组迭代器

numpy.ndarray.flat


In [35]:
for i in arr:
    print(i)

0
5
6
4
5
1
5
0


In [39]:
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [40]:
for arr1 in arr2:
    for i in arr1:
        print(i)

7
3
5
0
6
3
2
2
4
0
1
1


In [42]:
for i in arr2.flat:
    print(i)

7
3
5
0
6
3
2
2
4
0
1
1


### 数组扁平处理


numpy.ndarray.flatten() 返回一份展开的数组拷贝，对拷贝所做的修改不会影响原始数组

numpy.ravel() 展平的数组元素，返回一个展开的数组引用，修改会影响原始数组。

In [45]:
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [44]:
arr2.flatten()

array([7, 3, 5, 0, 6, 3, 2, 2, 4, 0, 1, 1])

In [46]:
arr2.ravel()

array([7, 3, 5, 0, 6, 3, 2, 2, 4, 0, 1, 1])

### 数组翻转

numpy.transpose 对换数组的维度

In [48]:
arr2.shape

(4, 3)

In [50]:
arr2

array([[7, 3, 5],
       [0, 6, 3],
       [2, 2, 4],
       [0, 1, 1]])

In [49]:
arr2.transpose([1,0])

array([[7, 0, 2, 0],
       [3, 6, 2, 1],
       [5, 3, 4, 1]])

## Numpy 数学函数

### 三角函数

np.sin(), np.cos(), np.tan()

接收的参数是弧度，不是角度

In [56]:
np.pi

3.141592653589793

In [58]:
# 生成一个取值范围在 -pi ~ pi 之间的数组
data = np.random.random(size=10)*2*np.pi - np.pi

In [60]:
data

array([-0.65724319, -0.59066276, -2.12718198, -2.563652  ,  1.23509994,
        0.53872679,  2.23327513, -1.18657566, -0.25970384,  2.01235196])

In [62]:
np.sin(data)

array([-0.61093667, -0.55691162, -0.84916947, -0.54630021,  0.94418113,
        0.51304353,  0.78847001, -0.92709084, -0.25679433,  0.90408796])

In [64]:
np.sin(90), np.sin(np.pi/2)

(0.8939966636005579, 1.0)

### 舍入函数

numpy.around()

- a: 数组
- decimals: 舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置

In [66]:
data = np.random.random(size=10)

In [67]:
np.around(data, 3)

array([0.094, 0.008, 0.029, 0.359, 0.693, 0.785, 0.434, 0.275, 0.697,
       0.892])

## 算数函数

加减乘除: add()，subtract()，multiply() 和 divide()

numpy.power() 幂运算，可以做开方运算

numpy.mode() 求余运算

np.log() 自然底数的对数
np.log2(), np.log10()

In [74]:
a1 = np.random.randint(0, 10, size=(5,3))
b1 = np.random.randint(0, 10, size=3)

In [75]:
np.add(a1, b1)

array([[ 9,  6,  5],
       [ 9, 11,  4],
       [ 4, 11,  8],
       [10, 10,  3],
       [11, 10,  4]])

In [78]:
data = np.random.randint(0, 10, size=5)
data

array([7, 7, 2, 6, 0])

In [81]:
data_s = np.power(data, 2)

In [82]:
np.power(data_s, 1/2)

array([7., 7., 2., 6., 0.])

In [84]:
np.mod(data, 2)

array([1, 1, 0, 0, 0], dtype=int32)

In [85]:
# 自然底数
np.e

2.718281828459045

In [87]:
np.log10()

C:\Users\Dancer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


nan

## Numpy 查找和排序

### 查找索引

numpy.argmax() 和 numpy.argmin()

In [88]:
data = np.random.randint(0, 100, size=10)
data

array([19, 60, 28, 48, 81, 39, 87, 62, 61, 19])

In [90]:
data.argmax(), data.argmin()

(6, 0)

### 条件查找

numpy.where() 函数返回输入数组中满足给定条件的元素的索引

In [91]:
data

array([19, 60, 28, 48, 81, 39, 87, 62, 61, 19])

In [ ]:
condition  条件  条件表达式

In [92]:
data > 60

array([False, False, False, False,  True, False,  True,  True,  True,
       False])

In [94]:
#  condition 参数就是一个条件表达式
condition = data > 60
np.where(condition)

(array([4, 6, 7, 8], dtype=int64),)

### 快速排序

np.sort()与ndarray.sort()都可以，但有区别：

- np.sort()不改变输入
- ndarray.sort()本地处理，不占用空间，但改变输入

numpy.sort() 函数返回输入数组的排序副本

In [95]:
arr

array([0, 5, 6, 4, 5, 1, 5, 0])

In [96]:
np.sort(arr)

array([0, 0, 1, 4, 5, 5, 5, 6])

In [97]:
arr

array([0, 5, 6, 4, 5, 1, 5, 0])

In [98]:
arr.sort()

In [99]:
arr

array([0, 0, 1, 4, 5, 5, 5, 6])

### 索引排序

numpy.argsort() 函数返回的是数组值从小到大的索引值。

In [100]:
data = np.random.randint(0, 10, size=5)
data

array([0, 9, 6, 4, 3])

In [101]:
np.argsort(data)

array([0, 4, 3, 2, 1], dtype=int64)

### 部分排序
np.partition(a,k)

有的时候我们不是对全部数据感兴趣，我们可能只对最小或最大的一部分感兴趣。
- 当k为正时，我们想要得到最小的k个数
- 当k为负时，我们想要得到最大的k个数

In [103]:
data = np.random.permutation(10000)

In [104]:
data

array([7261, 3486, 5101, ..., 6822, 2481, 6462])

In [106]:
np.partition(data, -2)[-2:]

array([9998, 9999])

In [108]:
np.partition(data, 2)[:2]

array([0, 1])